module.exports = {
  async up(queryInterface) {
    await queryInterface.bulkInsert('Reviews', [{
      place_id: 1,
      user_id: 1,
      title: 'очень клевое место',
      description: 'ездил на прошлых выходных, очень круто покатался',
      date: '2022-08-13',
      rating: 5,
    }, {
      place_id: 2,
      user_id: 1,
      title: 'место норм',
      description: 'ездил на прошлых выходных, с погодой не подфартило',
      date: '2022-08-14',
      rating: 4,
    }, {
      place_id: 3,
      user_id: 4,
      title: 'сойдет',
      description: 'ничо так',
      date: '2022-08-19',
      rating: 5,
    }, {
      place_id: 6,
      user_id: 2,
      title: 'сойдет',
      description: 'ничо так',
      date: '2022-08-19',
      rating: 3,
    }, {
      place_id: 5,
      user_id: 4,
      title: 'норм',
      description: 'just some text about this place',
      date: '2022-08-19',
      rating: 4,
    }, {
      place_id: 4,
      user_id: 3,
      title: 'класс',
      description: 'just some text about this place',
      date: '2022-08-19',
      rating: 5,
    }, {
      place_id: 3,
      user_id: 4,
      title: 'сойдет',
      description: 'just some text about this place',
      date: '2022-08-19',
      rating: 3,
    }, {
      place_id: 6,
      user_id: 3,
      title: 'норм',
      description: 'just some text about this place',
      date: '2022-08-19',
      rating: 5,
    }, {
      place_id: 2,
      user_id: 1,
      title: 'норм',
      description: 'just some text about this place',
      date: '2022-08-19',
      rating: 4,
    }, {
      place_id: 2,
      user_id: 2,
      title: 'не понравилось',
      description: 'just some text about this place',
      date: '2022-08-19',
      rating: 1,
    },
    {
      place_id: 7,
      user_id: 3,
      title: 'test',
      description: 'just some text about this place',
      date: '2022-10-19',
      rating: 5,
    },
    {
      place_id: 8,
      user_id: 2,
      title: 'test',
      description: 'just some text about this place',
      date: '2022-10-19',
      rating: 4,
    },
    {
      place_id: 9,
      user_id: 2,
      title: 'test',
      description: 'just some text about this place',
      date: '2022-10-19',
      rating: 4,
    },
    {
      place_id: 10,
      user_id: 2,
      title: 'test',
      description: 'just some text about this place',
      date: '2022-10-19',
      rating: 5,
    },
    {
      place_id: 11,
      user_id: 3,
      title: 'test',
      description: 'just some text about this place',
      date: '2022-10-19',
      rating: 5,
    },
    {
      place_id: 12,
      user_id: 3,
      title: 'test',
      description: 'just some text about this place',
      date: '2022-10-19',
      rating: 5,
    },
    {
      place_id: 12,
      user_id: 3,
      title: 'test',
      description: 'just some text about this place',
      date: '2022-10-19',
      rating: 5,
    },
    {
      place_id: 13,
      user_id: 3,
      title: 'test',
      description: 'just some text about this place',
      date: '2022-10-19',
      rating: 5,
    },
    {
      place_id: 14,
      user_id: 3,
      title: 'test',
      description: 'just some text about this place',
      date: '2022-10-19',
      rating: 5,
    },
    {
      place_id: 15,
      user_id: 3,
      title: 'test',
      description: 'just some text about this place',
      date: '2022-10-19',
      rating: 4,
    },
    {
      place_id: 16,
      user_id: 3,
      title: 'test',
      description: 'just some text about this place',
      date: '2022-10-19',
      rating: 4,
    },
    {
      place_id: 17,
      user_id: 3,
      title: 'test',
      description: 'just some text about this place',
      date: '2022-10-19',
      rating: 4,
    },
    {
      place_id: 18,
      user_id: 3,
      title: 'test',
      description: 'just some text about this place',
      date: '2022-10-19',
      rating: 3,
    },
    {
      place_id: 19,
      user_id: 3,
      title: 'test',
      description: 'just some text about this place',
      date: '2022-10-19',
      rating: 3,
    },
    {
      place_id: 20,
      user_id: 3,
      title: 'test',
      description: 'just some text about this place',
      date: '2022-10-19',
      rating: 5,
    },
    {
      place_id: 21,
      user_id: 3,
      title: 'test',
      description: 'just some text about this place',
      date: '2022-10-19',
      rating: 5,
    },
    {
      place_id: 22,
      user_id: 3,
      title: 'test',
      description: 'just some text about this place',
      date: '2022-10-19',
      rating: 4,
    },
    {
      place_id: 23,
      user_id: 3,
      title: 'test',
      description: 'just some text about this place',
      date: '2022-10-19',
      rating: 4,
    },
    {
      place_id: 24,
      user_id: 3,
      title: 'test',
      description: 'just some text about this place',
      date: '2022-10-19',
      rating: 3,
    },
    {
      place_id: 25,
      user_id: 1,
      title: 'test',
      description: 'just some text about this place',
      date: '2022-10-19',
      rating: 5,
    },
    {
      place_id: 25,
      user_id: 1,
      title: 'test',
      description: 'just some text about this place',
      date: '2022-10-19',
      rating: 5,
    },
    {
      place_id: 25,
      user_id: 1,
      title: 'test',
      description: 'just some text about this place',
      date: '2022-10-19',
      rating: 5,
    },
    {
      place_id: 26,
      user_id: 1,
      title: 'test',
      description: 'just some text about this place',
      date: '2022-10-19',
      rating: 4,
    },
    {
      place_id: 27,
      user_id: 1,
      title: 'test',
      description: 'just some text about this place',
      date: '2022-10-19',
      rating: 4,
    },
    {
      place_id: 28,
      user_id: 1,
      title: 'test',
      description: 'just some text about this place',
      date: '2022-10-19',
      rating: 4,
    },
    {
      place_id: 29,
      user_id: 1,
      title: 'test',
      description: 'just some text about this place',
      date: '2022-10-19',
      rating: 3,
    },
    {
      place_id: 30,
      user_id: 4,
      title: 'test',
      description: 'just some text about this place',
      date: '2022-10-19',
      rating: 5,
    },
    {
      place_id: 31,
      user_id: 4,
      title: 'test',
      description: 'just some text about this place',
      date: '2022-10-19',
      rating: 5,
    },
    {
      place_id: 32,
      user_id: 4,
      title: 'test',
      description: 'just some text about this place',
      date: '2022-10-19',
      rating: 5,
    },
    {
      place_id: 33,
      user_id: 4,
      title: 'test',
      description: 'just some text about this place',
      date: '2022-10-19',
      rating: 4,
    },
    {
      place_id: 33,
      user_id: 4,
      title: 'test',
      description: 'just some text about this place',
      date: '2022-10-19',
      rating: 3,
    },
    {
      place_id: 34,
      user_id: 4,
      title: 'test',
      description: 'just some text about this place',
      date: '2022-10-19',
      rating: 4,
    },
    {
      place_id: 35,
      user_id: 4,
      title: 'test',
      description: 'just some text about this place',
      date: '2022-10-19',
      rating: 3,
    },
    {
      place_id: 36,
      user_id: 2,
      title: 'test',
      description: 'just some text about this place',
      date: '2022-10-19',
      rating: 5,
    },
    {
      place_id: 37,
      user_id: 2,
      title: 'test',
      description: 'just some text about this place',
      date: '2022-10-19',
      rating: 5,
    },
    {
      place_id: 38,
      user_id: 2,
      title: 'test',
      description: 'just some text about this place',
      date: '2022-10-19',
      rating: 5,
    },
    {
      place_id: 39,
      user_id: 2,
      title: 'test',
      description: 'just some text about this place',
      date: '2022-10-19',
      rating: 5,
    },
    {
      place_id: 40,
      user_id: 2,
      title: 'test',
      description: 'just some text about this place',
      date: '2022-10-19',
      rating: 4,
    },
    {
      place_id: 41,
      user_id: 2,
      title: 'test',
      description: 'just some text about this place',
      date: '2022-10-19',
      rating: 3,
    },
    ], {});
  },

  async down(queryInterface) {
    await queryInterface.bulkDelete('Reviews', null, {});
  },
};
